package com.nexus.platform.security;

public enum Permission {
    USER_PROFILE_READ,
    USER_PROFILE_WRITE,
    USER_WALLET_READ,
    USER_LOGOUT,
    LIBRARY_READ,
    LIBRARY_WRITE,
    GAME_UPLOAD,
    GAME_DEVELOPER_READ,
    GAME_AUDIT_SUBMIT,
    GAME_VERSION_ROLLBACK,
    GAME_AUDIT_APPROVE,
    GAME_AUDIT_REJECT,
    AUDIT_LOG_READ,
    ANDROID_ADMIN_READ,
    ANDROID_ADMIN_WRITE
}
